# Generated by Django 5.2.4 on 2025-08-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='personal_skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FEIF_DB.personal_skill'),
        ),
    ]
