# Generated by Django 5.2.4 on 2025-08-02 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0002_personal_skill_character_personal_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AlterField(
            model_name='character',
            name='personal_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FEIF_DB.personal_skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personal_skill',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
