# Generated by Django 5.2.4 on 2025-08-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0003_remove_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='joined_charpter',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
