# Generated by Django 5.2.4 on 2025-08-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0004_character_joined_charpter'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
