# Generated by Django 5.2.4 on 2025-08-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0005_character_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='WeaponCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Weapon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='FEIF_DB.weaponcategory', verbose_name='WeaponsBelong')),
            ],
        ),
    ]
