# Generated by Django 5.2.4 on 2025-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0006_weaponcategory_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='avoid',
            field=models.IntegerField(default=0, verbose_name='Avoid'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='crit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Crit'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='dodge',
            field=models.IntegerField(default=0, verbose_name='Dodge'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='effect',
            field=models.CharField(blank=True, max_length=200, verbose_name='Effect'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='hit',
            field=models.IntegerField(default=0, verbose_name='Hit'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='weapon_icons/', verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='might',
            field=models.IntegerField(default=0, verbose_name='Might'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='range',
            field=models.CharField(blank=True, max_length=20, verbose_name='Range'),
        ),
    ]
