# Generated by Django 5.2.4 on 2025-08-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0007_weapon_avoid_weapon_crit_weapon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='level',
            field=models.CharField(max_length=5, verbose_name='Level'),
        ),
    ]
