# Generated by Django 5.2.4 on 2025-08-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0008_alter_weapon_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='obtain_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='Obtain Method'),
        ),
    ]
