# Generated by Django 5.2.4 on 2025-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0009_weapon_obtain_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='item_icons/')),
                ('durability', models.CharField(default='--', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('obtain_method', models.TextField(blank=True)),
            ],
        ),
    ]
