# Generated by Django 5.2.4 on 2025-08-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0010_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='durability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default='--', max_length=20),
        ),
    ]
