# Generated by Django 5.2.4 on 2025-08-05 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0011_alter_item_durability_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='skill_icons/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('learn_condition', models.TextField(blank=True, verbose_name='Normal Learn Condition')),
                ('source_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='FEIF_DB.job', verbose_name='Skill Source Job')),
            ],
        ),
    ]
