# Generated by Django 5.2.4 on 2025-08-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0012_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='icon',
            field=models.ImageField(default=1, upload_to='icons/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='join_condition',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='starting_weapon_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
