# Generated by Django 5.2.4 on 2025-08-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0013_character_icon_character_join_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='join_condition',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
