# Generated by Django 5.2.4 on 2025-08-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0015_character_base_defense_character_base_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='storyline',
            field=models.CharField(choices=[('A', 'White'), ('B', 'Dark'), ('C', 'Tomo')], default='A', max_length=1),
        ),
    ]
