# Generated by Django 5.2.4 on 2025-08-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0016_character_storyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Class_Traits',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='Weapon_Proficiency_Cap',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_defense',
            field=models.IntegerField(default=1, verbose_name='Defense Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_hp',
            field=models.IntegerField(default=1, verbose_name='HP Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_luck',
            field=models.IntegerField(default=1, verbose_name='Luck Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_magic',
            field=models.IntegerField(default=1, verbose_name='Magic Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_resistance',
            field=models.IntegerField(default=1, verbose_name='Resistance Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_skill',
            field=models.IntegerField(default=1, verbose_name='Skill Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_speed',
            field=models.IntegerField(default=1, verbose_name='Speed Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_strength',
            field=models.IntegerField(default=1, verbose_name='Strength Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cap_total',
            field=models.IntegerField(default=1, verbose_name='Total Cap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_defense',
            field=models.IntegerField(default=1, verbose_name='Defense Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_hp',
            field=models.IntegerField(default=1, verbose_name='HP Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_luck',
            field=models.IntegerField(default=1, verbose_name='Luck Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_magic',
            field=models.IntegerField(default=1, verbose_name='Magic Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_resistance',
            field=models.IntegerField(default=1, verbose_name='Resistance Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_skill',
            field=models.IntegerField(default=1, verbose_name='Skill Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_speed',
            field=models.IntegerField(default=1, verbose_name='Speed Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='growth_strength',
            field=models.IntegerField(default=1, verbose_name='Strength Growth Modifier (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill',
            field=models.ImageField(default=1, upload_to='job_skill/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('A', 'Base'), ('B', 'Promoted')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='movement',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
