# Generated by Django 5.2.4 on 2025-08-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0017_job_class_traits_job_weapon_proficiency_cap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_skill',
            new_name='job_skill1',
        ),
        migrations.AddField(
            model_name='job',
            name='job_skill2',
            field=models.ImageField(default=1, upload_to='job_skill/'),
            preserve_default=False,
        ),
    ]
