# Generated by Django 5.2.4 on 2025-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0018_rename_job_skill_job_job_skill1_job_job_skill2'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Allegiance',
            field=models.CharField(choices=[('A', 'Neutral'), ('B', 'Dark'), ('C', 'Light')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
