# Generated by Django 5.2.4 on 2025-08-09 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0020_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_skill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_skill1', to='FEIF_DB.skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_skill2', to='FEIF_DB.skill'),
        ),
    ]
