# Generated by Django 5.2.4 on 2025-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0021_alter_job_job_skill1_alter_job_job_skill2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='crit',
            field=models.CharField(default=1, verbose_name='Crit'),
            preserve_default=False,
        ),
    ]
