# Generated by Django 5.2.4 on 2025-08-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0022_alter_weapon_crit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='price',
            field=models.CharField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
