# Generated by Django 5.2.4 on 2025-08-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0023_alter_weapon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='might',
            field=models.CharField(verbose_name='Might'),
        ),
    ]
