# Generated by Django 5.2.4 on 2025-08-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0024_alter_weapon_might'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='avoid',
            field=models.CharField(default=0, verbose_name='Avoid'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='dodge',
            field=models.CharField(default=0, verbose_name='Dodge'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='hit',
            field=models.CharField(default=0, verbose_name='Hit'),
        ),
    ]
