# Generated by Django 5.2.4 on 2025-08-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0025_alter_weapon_avoid_alter_weapon_dodge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='obtain_method',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Obtain Method'),
        ),
    ]
