# Generated by Django 5.2.4 on 2025-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0026_alter_weapon_obtain_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='level',
            field=models.CharField(choices=[('A', 'Base'), ('B', 'Promoted'), ('C', 'Special')], max_length=10),
        ),
    ]
