# Generated by Django 5.2.4 on 2025-08-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0027_alter_job_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_skill1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_skill2',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, to='FEIF_DB.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='source_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_skills', to='FEIF_DB.job', verbose_name='Skill Source Job'),
        ),
    ]
