# Generated by Django 5.2.4 on 2025-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0028_remove_job_job_skill1_remove_job_job_skill2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='buddy_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='marriage_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='starting_class',
        ),
        migrations.AddField(
            model_name='character',
            name='buddy_class',
            field=models.ManyToManyField(blank=True, related_name='buddy_characters', to='FEIF_DB.job'),
        ),
        migrations.AddField(
            model_name='character',
            name='marriage_class',
            field=models.ManyToManyField(blank=True, related_name='marriage_characters', to='FEIF_DB.job'),
        ),
        migrations.AddField(
            model_name='character',
            name='starting_class',
            field=models.ManyToManyField(blank=True, related_name='starting_characters', to='FEIF_DB.job'),
        ),
    ]
