# Generated by Django 5.2.4 on 2025-08-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FEIF_DB', '0029_remove_character_buddy_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='join_condition',
        ),
    ]
